version: "3.3"
services:

  api:
    build: .
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./api:/app/api

    ## We do production deployment with https://github.com/nginx-proxy/nginx-proxy
    # environment:
    #   - VIRTUAL_HOST=fair-eval.semanticscience.org
    #   - LETSENCRYPT_HOST=fair-eval.semanticscience.org
    #   - VIRTUAL_PORT=80
