version: "3.3"
services:

  api:
    build: .
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./api:/app/api
      - ./metrics_tests:/app/metrics_tests
    command: /start-reload.sh
